=== hassanec3u/sendingXmlSignedBetweenThread/src/database/entreprise.dtd
<!ELEMENT entreprise (employe+)>
<!ELEMENT employe (nom, poste, email, age, salaire, date_debut)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT poste (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT salaire (#PCDATA)>
<!ELEMENT date_debut (#PCDATA)>

=== hassanec3u/sendingXmlSignedBetweenThread/src/database/bd_bob.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entreprise SYSTEM "entreprise.dtd">
<entreprise>
    <employe>
        <nom>Robert Johnson</nom>
        <poste>Assistant</poste>
        <email>robert.johnson@example.com</email>
        <age>32</age>
        <salaire>45000</salaire>
        <date_debut>2021-11-10</date_debut>
    </employe>


    <employe>
        <nom>Sarah Lee</nom>
        <poste>Analyste financier</poste>
        <email>sarah.lee@example.com</email>
        <age>29</age>
        <salaire>58000</salaire>
        <date_debut>2022-08-05</date_debut>
    </employe>
</entreprise>

=== hassanec3u/sendingXmlSignedBetweenThread/src/database/bd_alice.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE entreprise SYSTEM "entreprise.dtd">
<entreprise >
    <employe>
        <nom>John Doe</nom>
        <poste>Manager</poste>
        <email>john.doe@example.com</email>
        <age>35</age>
        <salaire>60000</salaire>
        <date_debut>2022-05-15</date_debut>
    </employe>
    <employe >
        <nom>Jane Smith</nom>
        <poste>Ing√©nieur</poste>
        <email>jane.smith@example.com</email>
        <age>28</age>
        <salaire>55000</salaire>
        <date_debut>2023-02-20</date_debut>
    </employe>
</entreprise>
